# Generated by Django 4.0.1 on 2022-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
    ]
