# Generated by Django 4.0.1 on 2022-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_phone_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='diag_display',
            field=models.CharField(default='5', max_length=5, verbose_name='Диагональ'),
        ),
    ]
